/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.jppjson.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Add Element</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.jppjson.myDsl.AddElement#getElement <em>Element</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.jppjson.myDsl.MyDslPackage#getAddElement()
 * @model
 * @generated
 */
public interface AddElement extends Command
{
  /**
   * Returns the value of the '<em><b>Element</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Element</em>' containment reference.
   * @see #setElement(Element)
   * @see org.xtext.example.jppjson.myDsl.MyDslPackage#getAddElement_Element()
   * @model containment="true"
   * @generated
   */
  Element getElement();

  /**
   * Sets the value of the '{@link org.xtext.example.jppjson.myDsl.AddElement#getElement <em>Element</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Element</em>' containment reference.
   * @see #getElement()
   * @generated
   */
  void setElement(Element value);

} // AddElement
