/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.jppjson.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Bin Exp</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.jppjson.myDsl.BinExp#getVal <em>Val</em>}</li>
 *   <li>{@link org.xtext.example.jppjson.myDsl.BinExp#getRval <em>Rval</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.jppjson.myDsl.MyDslPackage#getBinExp()
 * @model
 * @generated
 */
public interface BinExp extends Expression
{
  /**
   * Returns the value of the '<em><b>Val</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Val</em>' attribute.
   * @see #setVal(String)
   * @see org.xtext.example.jppjson.myDsl.MyDslPackage#getBinExp_Val()
   * @model
   * @generated
   */
  String getVal();

  /**
   * Sets the value of the '{@link org.xtext.example.jppjson.myDsl.BinExp#getVal <em>Val</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Val</em>' attribute.
   * @see #getVal()
   * @generated
   */
  void setVal(String value);

  /**
   * Returns the value of the '<em><b>Rval</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Rval</em>' attribute.
   * @see #setRval(String)
   * @see org.xtext.example.jppjson.myDsl.MyDslPackage#getBinExp_Rval()
   * @model
   * @generated
   */
  String getRval();

  /**
   * Sets the value of the '{@link org.xtext.example.jppjson.myDsl.BinExp#getRval <em>Rval</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Rval</em>' attribute.
   * @see #getRval()
   * @generated
   */
  void setRval(String value);

} // BinExp
