/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.jppjson.myDsl;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>JArray</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.jppjson.myDsl.JArray#getExpression <em>Expression</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.jppjson.myDsl.MyDslPackage#getJArray()
 * @model
 * @generated
 */
public interface JArray extends Entity
{
  /**
   * Returns the value of the '<em><b>Expression</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.jppjson.myDsl.Expression}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expression</em>' containment reference list.
   * @see org.xtext.example.jppjson.myDsl.MyDslPackage#getJArray_Expression()
   * @model containment="true"
   * @generated
   */
  EList<Expression> getExpression();

} // JArray
