/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.jppjson.myDsl;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>JObject</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.jppjson.myDsl.JObject#getElement <em>Element</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.jppjson.myDsl.MyDslPackage#getJObject()
 * @model
 * @generated
 */
public interface JObject extends Entity
{
  /**
   * Returns the value of the '<em><b>Element</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.jppjson.myDsl.Element}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Element</em>' containment reference list.
   * @see org.xtext.example.jppjson.myDsl.MyDslPackage#getJObject_Element()
   * @model containment="true"
   * @generated
   */
  EList<Element> getElement();

} // JObject
