/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.jppjson.myDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Loadfile</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.jppjson.myDsl.Loadfile#getPath <em>Path</em>}</li>
 *   <li>{@link org.xtext.example.jppjson.myDsl.Loadfile#getCommands <em>Commands</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.jppjson.myDsl.MyDslPackage#getLoadfile()
 * @model
 * @generated
 */
public interface Loadfile extends EObject
{
  /**
   * Returns the value of the '<em><b>Path</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Path</em>' attribute.
   * @see #setPath(String)
   * @see org.xtext.example.jppjson.myDsl.MyDslPackage#getLoadfile_Path()
   * @model
   * @generated
   */
  String getPath();

  /**
   * Sets the value of the '{@link org.xtext.example.jppjson.myDsl.Loadfile#getPath <em>Path</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Path</em>' attribute.
   * @see #getPath()
   * @generated
   */
  void setPath(String value);

  /**
   * Returns the value of the '<em><b>Commands</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.jppjson.myDsl.Command}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Commands</em>' containment reference list.
   * @see org.xtext.example.jppjson.myDsl.MyDslPackage#getLoadfile_Commands()
   * @model containment="true"
   * @generated
   */
  EList<Command> getCommands();

} // Loadfile
