/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.jppjson.myDsl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.example.jppjson.myDsl.MyDslFactory
 * @model kind="package"
 * @generated
 */
public interface MyDslPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "myDsl";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/example/jppjson/MyDsl";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "myDsl";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  MyDslPackage eINSTANCE = org.xtext.example.jppjson.myDsl.impl.MyDslPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.example.jppjson.myDsl.impl.ExpressionImpl <em>Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.jppjson.myDsl.impl.ExpressionImpl
   * @see org.xtext.example.jppjson.myDsl.impl.MyDslPackageImpl#getExpression()
   * @generated
   */
  int EXPRESSION = 0;

  /**
   * The number of structural features of the '<em>Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.example.jppjson.myDsl.impl.EntityImpl <em>Entity</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.jppjson.myDsl.impl.EntityImpl
   * @see org.xtext.example.jppjson.myDsl.impl.MyDslPackageImpl#getEntity()
   * @generated
   */
  int ENTITY = 1;

  /**
   * The number of structural features of the '<em>Entity</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTITY_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.example.jppjson.myDsl.impl.ElementImpl <em>Element</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.jppjson.myDsl.impl.ElementImpl
   * @see org.xtext.example.jppjson.myDsl.impl.MyDslPackageImpl#getElement()
   * @generated
   */
  int ELEMENT = 2;

  /**
   * The feature id for the '<em><b>Key</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELEMENT__KEY = 0;

  /**
   * The feature id for the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELEMENT__VALUE = 1;

  /**
   * The number of structural features of the '<em>Element</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELEMENT_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.jppjson.myDsl.impl.ValueImpl <em>Value</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.jppjson.myDsl.impl.ValueImpl
   * @see org.xtext.example.jppjson.myDsl.impl.MyDslPackageImpl#getValue()
   * @generated
   */
  int VALUE = 3;

  /**
   * The number of structural features of the '<em>Value</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VALUE_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.example.jppjson.myDsl.impl.JsonStringImpl <em>Json String</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.jppjson.myDsl.impl.JsonStringImpl
   * @see org.xtext.example.jppjson.myDsl.impl.MyDslPackageImpl#getJsonString()
   * @generated
   */
  int JSON_STRING = 4;

  /**
   * The feature id for the '<em><b>Val</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JSON_STRING__VAL = VALUE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Json String</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JSON_STRING_FEATURE_COUNT = VALUE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.jppjson.myDsl.impl.JsonBooleanImpl <em>Json Boolean</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.jppjson.myDsl.impl.JsonBooleanImpl
   * @see org.xtext.example.jppjson.myDsl.impl.MyDslPackageImpl#getJsonBoolean()
   * @generated
   */
  int JSON_BOOLEAN = 5;

  /**
   * The feature id for the '<em><b>Val</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JSON_BOOLEAN__VAL = VALUE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Json Boolean</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JSON_BOOLEAN_FEATURE_COUNT = VALUE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.jppjson.myDsl.impl.JsonEmptyImpl <em>Json Empty</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.jppjson.myDsl.impl.JsonEmptyImpl
   * @see org.xtext.example.jppjson.myDsl.impl.MyDslPackageImpl#getJsonEmpty()
   * @generated
   */
  int JSON_EMPTY = 6;

  /**
   * The feature id for the '<em><b>Val</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JSON_EMPTY__VAL = VALUE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Json Empty</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JSON_EMPTY_FEATURE_COUNT = VALUE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.jppjson.myDsl.impl.JsonIntegerImpl <em>Json Integer</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.jppjson.myDsl.impl.JsonIntegerImpl
   * @see org.xtext.example.jppjson.myDsl.impl.MyDslPackageImpl#getJsonInteger()
   * @generated
   */
  int JSON_INTEGER = 7;

  /**
   * The feature id for the '<em><b>Val</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JSON_INTEGER__VAL = VALUE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Json Integer</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JSON_INTEGER_FEATURE_COUNT = VALUE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.jppjson.myDsl.impl.JObjectImpl <em>JObject</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.jppjson.myDsl.impl.JObjectImpl
   * @see org.xtext.example.jppjson.myDsl.impl.MyDslPackageImpl#getJObject()
   * @generated
   */
  int JOBJECT = 8;

  /**
   * The feature id for the '<em><b>Element</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JOBJECT__ELEMENT = ENTITY_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>JObject</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JOBJECT_FEATURE_COUNT = ENTITY_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.jppjson.myDsl.impl.JArrayImpl <em>JArray</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.jppjson.myDsl.impl.JArrayImpl
   * @see org.xtext.example.jppjson.myDsl.impl.MyDslPackageImpl#getJArray()
   * @generated
   */
  int JARRAY = 9;

  /**
   * The feature id for the '<em><b>Expression</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JARRAY__EXPRESSION = ENTITY_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>JArray</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JARRAY_FEATURE_COUNT = ENTITY_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.jppjson.myDsl.impl.BinExpImpl <em>Bin Exp</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.jppjson.myDsl.impl.BinExpImpl
   * @see org.xtext.example.jppjson.myDsl.impl.MyDslPackageImpl#getBinExp()
   * @generated
   */
  int BIN_EXP = 10;

  /**
   * The feature id for the '<em><b>Val</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BIN_EXP__VAL = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Rval</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BIN_EXP__RVAL = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Bin Exp</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BIN_EXP_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 2;


  /**
   * Returns the meta object for class '{@link org.xtext.example.jppjson.myDsl.Expression <em>Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Expression</em>'.
   * @see org.xtext.example.jppjson.myDsl.Expression
   * @generated
   */
  EClass getExpression();

  /**
   * Returns the meta object for class '{@link org.xtext.example.jppjson.myDsl.Entity <em>Entity</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Entity</em>'.
   * @see org.xtext.example.jppjson.myDsl.Entity
   * @generated
   */
  EClass getEntity();

  /**
   * Returns the meta object for class '{@link org.xtext.example.jppjson.myDsl.Element <em>Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Element</em>'.
   * @see org.xtext.example.jppjson.myDsl.Element
   * @generated
   */
  EClass getElement();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.jppjson.myDsl.Element#getKey <em>Key</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Key</em>'.
   * @see org.xtext.example.jppjson.myDsl.Element#getKey()
   * @see #getElement()
   * @generated
   */
  EAttribute getElement_Key();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.jppjson.myDsl.Element#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Value</em>'.
   * @see org.xtext.example.jppjson.myDsl.Element#getValue()
   * @see #getElement()
   * @generated
   */
  EReference getElement_Value();

  /**
   * Returns the meta object for class '{@link org.xtext.example.jppjson.myDsl.Value <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Value</em>'.
   * @see org.xtext.example.jppjson.myDsl.Value
   * @generated
   */
  EClass getValue();

  /**
   * Returns the meta object for class '{@link org.xtext.example.jppjson.myDsl.JsonString <em>Json String</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Json String</em>'.
   * @see org.xtext.example.jppjson.myDsl.JsonString
   * @generated
   */
  EClass getJsonString();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.jppjson.myDsl.JsonString#getVal <em>Val</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Val</em>'.
   * @see org.xtext.example.jppjson.myDsl.JsonString#getVal()
   * @see #getJsonString()
   * @generated
   */
  EAttribute getJsonString_Val();

  /**
   * Returns the meta object for class '{@link org.xtext.example.jppjson.myDsl.JsonBoolean <em>Json Boolean</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Json Boolean</em>'.
   * @see org.xtext.example.jppjson.myDsl.JsonBoolean
   * @generated
   */
  EClass getJsonBoolean();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.jppjson.myDsl.JsonBoolean#getVal <em>Val</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Val</em>'.
   * @see org.xtext.example.jppjson.myDsl.JsonBoolean#getVal()
   * @see #getJsonBoolean()
   * @generated
   */
  EAttribute getJsonBoolean_Val();

  /**
   * Returns the meta object for class '{@link org.xtext.example.jppjson.myDsl.JsonEmpty <em>Json Empty</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Json Empty</em>'.
   * @see org.xtext.example.jppjson.myDsl.JsonEmpty
   * @generated
   */
  EClass getJsonEmpty();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.jppjson.myDsl.JsonEmpty#getVal <em>Val</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Val</em>'.
   * @see org.xtext.example.jppjson.myDsl.JsonEmpty#getVal()
   * @see #getJsonEmpty()
   * @generated
   */
  EAttribute getJsonEmpty_Val();

  /**
   * Returns the meta object for class '{@link org.xtext.example.jppjson.myDsl.JsonInteger <em>Json Integer</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Json Integer</em>'.
   * @see org.xtext.example.jppjson.myDsl.JsonInteger
   * @generated
   */
  EClass getJsonInteger();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.jppjson.myDsl.JsonInteger#getVal <em>Val</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Val</em>'.
   * @see org.xtext.example.jppjson.myDsl.JsonInteger#getVal()
   * @see #getJsonInteger()
   * @generated
   */
  EAttribute getJsonInteger_Val();

  /**
   * Returns the meta object for class '{@link org.xtext.example.jppjson.myDsl.JObject <em>JObject</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>JObject</em>'.
   * @see org.xtext.example.jppjson.myDsl.JObject
   * @generated
   */
  EClass getJObject();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.jppjson.myDsl.JObject#getElement <em>Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Element</em>'.
   * @see org.xtext.example.jppjson.myDsl.JObject#getElement()
   * @see #getJObject()
   * @generated
   */
  EReference getJObject_Element();

  /**
   * Returns the meta object for class '{@link org.xtext.example.jppjson.myDsl.JArray <em>JArray</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>JArray</em>'.
   * @see org.xtext.example.jppjson.myDsl.JArray
   * @generated
   */
  EClass getJArray();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.jppjson.myDsl.JArray#getExpression <em>Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Expression</em>'.
   * @see org.xtext.example.jppjson.myDsl.JArray#getExpression()
   * @see #getJArray()
   * @generated
   */
  EReference getJArray_Expression();

  /**
   * Returns the meta object for class '{@link org.xtext.example.jppjson.myDsl.BinExp <em>Bin Exp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Bin Exp</em>'.
   * @see org.xtext.example.jppjson.myDsl.BinExp
   * @generated
   */
  EClass getBinExp();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.jppjson.myDsl.BinExp#getVal <em>Val</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Val</em>'.
   * @see org.xtext.example.jppjson.myDsl.BinExp#getVal()
   * @see #getBinExp()
   * @generated
   */
  EAttribute getBinExp_Val();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.jppjson.myDsl.BinExp#getRval <em>Rval</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Rval</em>'.
   * @see org.xtext.example.jppjson.myDsl.BinExp#getRval()
   * @see #getBinExp()
   * @generated
   */
  EAttribute getBinExp_Rval();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  MyDslFactory getMyDslFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.example.jppjson.myDsl.impl.ExpressionImpl <em>Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.jppjson.myDsl.impl.ExpressionImpl
     * @see org.xtext.example.jppjson.myDsl.impl.MyDslPackageImpl#getExpression()
     * @generated
     */
    EClass EXPRESSION = eINSTANCE.getExpression();

    /**
     * The meta object literal for the '{@link org.xtext.example.jppjson.myDsl.impl.EntityImpl <em>Entity</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.jppjson.myDsl.impl.EntityImpl
     * @see org.xtext.example.jppjson.myDsl.impl.MyDslPackageImpl#getEntity()
     * @generated
     */
    EClass ENTITY = eINSTANCE.getEntity();

    /**
     * The meta object literal for the '{@link org.xtext.example.jppjson.myDsl.impl.ElementImpl <em>Element</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.jppjson.myDsl.impl.ElementImpl
     * @see org.xtext.example.jppjson.myDsl.impl.MyDslPackageImpl#getElement()
     * @generated
     */
    EClass ELEMENT = eINSTANCE.getElement();

    /**
     * The meta object literal for the '<em><b>Key</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ELEMENT__KEY = eINSTANCE.getElement_Key();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ELEMENT__VALUE = eINSTANCE.getElement_Value();

    /**
     * The meta object literal for the '{@link org.xtext.example.jppjson.myDsl.impl.ValueImpl <em>Value</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.jppjson.myDsl.impl.ValueImpl
     * @see org.xtext.example.jppjson.myDsl.impl.MyDslPackageImpl#getValue()
     * @generated
     */
    EClass VALUE = eINSTANCE.getValue();

    /**
     * The meta object literal for the '{@link org.xtext.example.jppjson.myDsl.impl.JsonStringImpl <em>Json String</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.jppjson.myDsl.impl.JsonStringImpl
     * @see org.xtext.example.jppjson.myDsl.impl.MyDslPackageImpl#getJsonString()
     * @generated
     */
    EClass JSON_STRING = eINSTANCE.getJsonString();

    /**
     * The meta object literal for the '<em><b>Val</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute JSON_STRING__VAL = eINSTANCE.getJsonString_Val();

    /**
     * The meta object literal for the '{@link org.xtext.example.jppjson.myDsl.impl.JsonBooleanImpl <em>Json Boolean</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.jppjson.myDsl.impl.JsonBooleanImpl
     * @see org.xtext.example.jppjson.myDsl.impl.MyDslPackageImpl#getJsonBoolean()
     * @generated
     */
    EClass JSON_BOOLEAN = eINSTANCE.getJsonBoolean();

    /**
     * The meta object literal for the '<em><b>Val</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute JSON_BOOLEAN__VAL = eINSTANCE.getJsonBoolean_Val();

    /**
     * The meta object literal for the '{@link org.xtext.example.jppjson.myDsl.impl.JsonEmptyImpl <em>Json Empty</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.jppjson.myDsl.impl.JsonEmptyImpl
     * @see org.xtext.example.jppjson.myDsl.impl.MyDslPackageImpl#getJsonEmpty()
     * @generated
     */
    EClass JSON_EMPTY = eINSTANCE.getJsonEmpty();

    /**
     * The meta object literal for the '<em><b>Val</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute JSON_EMPTY__VAL = eINSTANCE.getJsonEmpty_Val();

    /**
     * The meta object literal for the '{@link org.xtext.example.jppjson.myDsl.impl.JsonIntegerImpl <em>Json Integer</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.jppjson.myDsl.impl.JsonIntegerImpl
     * @see org.xtext.example.jppjson.myDsl.impl.MyDslPackageImpl#getJsonInteger()
     * @generated
     */
    EClass JSON_INTEGER = eINSTANCE.getJsonInteger();

    /**
     * The meta object literal for the '<em><b>Val</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute JSON_INTEGER__VAL = eINSTANCE.getJsonInteger_Val();

    /**
     * The meta object literal for the '{@link org.xtext.example.jppjson.myDsl.impl.JObjectImpl <em>JObject</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.jppjson.myDsl.impl.JObjectImpl
     * @see org.xtext.example.jppjson.myDsl.impl.MyDslPackageImpl#getJObject()
     * @generated
     */
    EClass JOBJECT = eINSTANCE.getJObject();

    /**
     * The meta object literal for the '<em><b>Element</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference JOBJECT__ELEMENT = eINSTANCE.getJObject_Element();

    /**
     * The meta object literal for the '{@link org.xtext.example.jppjson.myDsl.impl.JArrayImpl <em>JArray</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.jppjson.myDsl.impl.JArrayImpl
     * @see org.xtext.example.jppjson.myDsl.impl.MyDslPackageImpl#getJArray()
     * @generated
     */
    EClass JARRAY = eINSTANCE.getJArray();

    /**
     * The meta object literal for the '<em><b>Expression</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference JARRAY__EXPRESSION = eINSTANCE.getJArray_Expression();

    /**
     * The meta object literal for the '{@link org.xtext.example.jppjson.myDsl.impl.BinExpImpl <em>Bin Exp</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.jppjson.myDsl.impl.BinExpImpl
     * @see org.xtext.example.jppjson.myDsl.impl.MyDslPackageImpl#getBinExp()
     * @generated
     */
    EClass BIN_EXP = eINSTANCE.getBinExp();

    /**
     * The meta object literal for the '<em><b>Val</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BIN_EXP__VAL = eINSTANCE.getBinExp_Val();

    /**
     * The meta object literal for the '<em><b>Rval</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BIN_EXP__RVAL = eINSTANCE.getBinExp_Rval();

  }

} //MyDslPackage
