/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.jppjson.myDsl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.example.jppjson.myDsl.MyDslFactory
 * @model kind="package"
 * @generated
 */
public interface MyDslPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "myDsl";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/example/jppjson/MyDsl";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "myDsl";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  MyDslPackage eINSTANCE = org.xtext.example.jppjson.myDsl.impl.MyDslPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.example.jppjson.myDsl.impl.ProgrammeImpl <em>Programme</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.jppjson.myDsl.impl.ProgrammeImpl
   * @see org.xtext.example.jppjson.myDsl.impl.MyDslPackageImpl#getProgramme()
   * @generated
   */
  int PROGRAMME = 0;

  /**
   * The feature id for the '<em><b>Loadfiles</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAMME__LOADFILES = 0;

  /**
   * The number of structural features of the '<em>Programme</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAMME_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.jppjson.myDsl.impl.LoadfileImpl <em>Loadfile</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.jppjson.myDsl.impl.LoadfileImpl
   * @see org.xtext.example.jppjson.myDsl.impl.MyDslPackageImpl#getLoadfile()
   * @generated
   */
  int LOADFILE = 1;

  /**
   * The feature id for the '<em><b>Path</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOADFILE__PATH = 0;

  /**
   * The feature id for the '<em><b>Commands</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOADFILE__COMMANDS = 1;

  /**
   * The number of structural features of the '<em>Loadfile</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOADFILE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.jppjson.myDsl.impl.CommandImpl <em>Command</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.jppjson.myDsl.impl.CommandImpl
   * @see org.xtext.example.jppjson.myDsl.impl.MyDslPackageImpl#getCommand()
   * @generated
   */
  int COMMAND = 2;

  /**
   * The number of structural features of the '<em>Command</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMAND_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.example.jppjson.myDsl.impl.ReadImpl <em>Read</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.jppjson.myDsl.impl.ReadImpl
   * @see org.xtext.example.jppjson.myDsl.impl.MyDslPackageImpl#getRead()
   * @generated
   */
  int READ = 3;

  /**
   * The feature id for the '<em><b>Path</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int READ__PATH = COMMAND_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Read</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int READ_FEATURE_COUNT = COMMAND_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.jppjson.myDsl.impl.AddElementImpl <em>Add Element</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.jppjson.myDsl.impl.AddElementImpl
   * @see org.xtext.example.jppjson.myDsl.impl.MyDslPackageImpl#getAddElement()
   * @generated
   */
  int ADD_ELEMENT = 4;

  /**
   * The feature id for the '<em><b>Element</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADD_ELEMENT__ELEMENT = COMMAND_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Add Element</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADD_ELEMENT_FEATURE_COUNT = COMMAND_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.jppjson.myDsl.impl.RemoveElementImpl <em>Remove Element</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.jppjson.myDsl.impl.RemoveElementImpl
   * @see org.xtext.example.jppjson.myDsl.impl.MyDslPackageImpl#getRemoveElement()
   * @generated
   */
  int REMOVE_ELEMENT = 5;

  /**
   * The feature id for the '<em><b>Key</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REMOVE_ELEMENT__KEY = COMMAND_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Remove Element</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REMOVE_ELEMENT_FEATURE_COUNT = COMMAND_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.jppjson.myDsl.impl.EditObjectImpl <em>Edit Object</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.jppjson.myDsl.impl.EditObjectImpl
   * @see org.xtext.example.jppjson.myDsl.impl.MyDslPackageImpl#getEditObject()
   * @generated
   */
  int EDIT_OBJECT = 6;

  /**
   * The feature id for the '<em><b>Key</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EDIT_OBJECT__KEY = COMMAND_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EDIT_OBJECT__VALUE = COMMAND_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Edit Object</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EDIT_OBJECT_FEATURE_COUNT = COMMAND_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.jppjson.myDsl.impl.ToStringImpl <em>To String</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.jppjson.myDsl.impl.ToStringImpl
   * @see org.xtext.example.jppjson.myDsl.impl.MyDslPackageImpl#getToString()
   * @generated
   */
  int TO_STRING = 7;

  /**
   * The feature id for the '<em><b>Path</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TO_STRING__PATH = COMMAND_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>To String</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TO_STRING_FEATURE_COUNT = COMMAND_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.jppjson.myDsl.impl.ToCSVImpl <em>To CSV</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.jppjson.myDsl.impl.ToCSVImpl
   * @see org.xtext.example.jppjson.myDsl.impl.MyDslPackageImpl#getToCSV()
   * @generated
   */
  int TO_CSV = 8;

  /**
   * The feature id for the '<em><b>Path</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TO_CSV__PATH = COMMAND_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>To CSV</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TO_CSV_FEATURE_COUNT = COMMAND_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.jppjson.myDsl.impl.ExpressionImpl <em>Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.jppjson.myDsl.impl.ExpressionImpl
   * @see org.xtext.example.jppjson.myDsl.impl.MyDslPackageImpl#getExpression()
   * @generated
   */
  int EXPRESSION = 9;

  /**
   * The number of structural features of the '<em>Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.example.jppjson.myDsl.impl.EntityImpl <em>Entity</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.jppjson.myDsl.impl.EntityImpl
   * @see org.xtext.example.jppjson.myDsl.impl.MyDslPackageImpl#getEntity()
   * @generated
   */
  int ENTITY = 10;

  /**
   * The number of structural features of the '<em>Entity</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTITY_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.example.jppjson.myDsl.impl.ElementImpl <em>Element</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.jppjson.myDsl.impl.ElementImpl
   * @see org.xtext.example.jppjson.myDsl.impl.MyDslPackageImpl#getElement()
   * @generated
   */
  int ELEMENT = 11;

  /**
   * The feature id for the '<em><b>Key</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELEMENT__KEY = 0;

  /**
   * The feature id for the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELEMENT__VALUE = 1;

  /**
   * The number of structural features of the '<em>Element</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELEMENT_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.jppjson.myDsl.impl.ValueImpl <em>Value</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.jppjson.myDsl.impl.ValueImpl
   * @see org.xtext.example.jppjson.myDsl.impl.MyDslPackageImpl#getValue()
   * @generated
   */
  int VALUE = 12;

  /**
   * The number of structural features of the '<em>Value</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VALUE_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.example.jppjson.myDsl.impl.JsonStringImpl <em>Json String</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.jppjson.myDsl.impl.JsonStringImpl
   * @see org.xtext.example.jppjson.myDsl.impl.MyDslPackageImpl#getJsonString()
   * @generated
   */
  int JSON_STRING = 13;

  /**
   * The feature id for the '<em><b>Val</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JSON_STRING__VAL = VALUE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Json String</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JSON_STRING_FEATURE_COUNT = VALUE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.jppjson.myDsl.impl.JsonBooleanImpl <em>Json Boolean</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.jppjson.myDsl.impl.JsonBooleanImpl
   * @see org.xtext.example.jppjson.myDsl.impl.MyDslPackageImpl#getJsonBoolean()
   * @generated
   */
  int JSON_BOOLEAN = 14;

  /**
   * The feature id for the '<em><b>Val</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JSON_BOOLEAN__VAL = VALUE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Json Boolean</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JSON_BOOLEAN_FEATURE_COUNT = VALUE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.jppjson.myDsl.impl.JsonEmptyImpl <em>Json Empty</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.jppjson.myDsl.impl.JsonEmptyImpl
   * @see org.xtext.example.jppjson.myDsl.impl.MyDslPackageImpl#getJsonEmpty()
   * @generated
   */
  int JSON_EMPTY = 15;

  /**
   * The feature id for the '<em><b>Val</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JSON_EMPTY__VAL = VALUE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Json Empty</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JSON_EMPTY_FEATURE_COUNT = VALUE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.jppjson.myDsl.impl.JsonIntegerImpl <em>Json Integer</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.jppjson.myDsl.impl.JsonIntegerImpl
   * @see org.xtext.example.jppjson.myDsl.impl.MyDslPackageImpl#getJsonInteger()
   * @generated
   */
  int JSON_INTEGER = 16;

  /**
   * The feature id for the '<em><b>Val</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JSON_INTEGER__VAL = VALUE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Json Integer</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JSON_INTEGER_FEATURE_COUNT = VALUE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.jppjson.myDsl.impl.JObjectImpl <em>JObject</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.jppjson.myDsl.impl.JObjectImpl
   * @see org.xtext.example.jppjson.myDsl.impl.MyDslPackageImpl#getJObject()
   * @generated
   */
  int JOBJECT = 17;

  /**
   * The feature id for the '<em><b>Element</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JOBJECT__ELEMENT = ENTITY_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>JObject</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JOBJECT_FEATURE_COUNT = ENTITY_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.jppjson.myDsl.impl.JArrayImpl <em>JArray</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.jppjson.myDsl.impl.JArrayImpl
   * @see org.xtext.example.jppjson.myDsl.impl.MyDslPackageImpl#getJArray()
   * @generated
   */
  int JARRAY = 18;

  /**
   * The feature id for the '<em><b>Expression</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JARRAY__EXPRESSION = ENTITY_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>JArray</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JARRAY_FEATURE_COUNT = ENTITY_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.jppjson.myDsl.impl.BinExpImpl <em>Bin Exp</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.jppjson.myDsl.impl.BinExpImpl
   * @see org.xtext.example.jppjson.myDsl.impl.MyDslPackageImpl#getBinExp()
   * @generated
   */
  int BIN_EXP = 19;

  /**
   * The feature id for the '<em><b>Val</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BIN_EXP__VAL = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Rval</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BIN_EXP__RVAL = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Bin Exp</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BIN_EXP_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 2;


  /**
   * Returns the meta object for class '{@link org.xtext.example.jppjson.myDsl.Programme <em>Programme</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Programme</em>'.
   * @see org.xtext.example.jppjson.myDsl.Programme
   * @generated
   */
  EClass getProgramme();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.jppjson.myDsl.Programme#getLoadfiles <em>Loadfiles</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Loadfiles</em>'.
   * @see org.xtext.example.jppjson.myDsl.Programme#getLoadfiles()
   * @see #getProgramme()
   * @generated
   */
  EReference getProgramme_Loadfiles();

  /**
   * Returns the meta object for class '{@link org.xtext.example.jppjson.myDsl.Loadfile <em>Loadfile</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Loadfile</em>'.
   * @see org.xtext.example.jppjson.myDsl.Loadfile
   * @generated
   */
  EClass getLoadfile();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.jppjson.myDsl.Loadfile#getPath <em>Path</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Path</em>'.
   * @see org.xtext.example.jppjson.myDsl.Loadfile#getPath()
   * @see #getLoadfile()
   * @generated
   */
  EAttribute getLoadfile_Path();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.jppjson.myDsl.Loadfile#getCommands <em>Commands</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Commands</em>'.
   * @see org.xtext.example.jppjson.myDsl.Loadfile#getCommands()
   * @see #getLoadfile()
   * @generated
   */
  EReference getLoadfile_Commands();

  /**
   * Returns the meta object for class '{@link org.xtext.example.jppjson.myDsl.Command <em>Command</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Command</em>'.
   * @see org.xtext.example.jppjson.myDsl.Command
   * @generated
   */
  EClass getCommand();

  /**
   * Returns the meta object for class '{@link org.xtext.example.jppjson.myDsl.Read <em>Read</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Read</em>'.
   * @see org.xtext.example.jppjson.myDsl.Read
   * @generated
   */
  EClass getRead();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.jppjson.myDsl.Read#getPath <em>Path</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Path</em>'.
   * @see org.xtext.example.jppjson.myDsl.Read#getPath()
   * @see #getRead()
   * @generated
   */
  EAttribute getRead_Path();

  /**
   * Returns the meta object for class '{@link org.xtext.example.jppjson.myDsl.AddElement <em>Add Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Add Element</em>'.
   * @see org.xtext.example.jppjson.myDsl.AddElement
   * @generated
   */
  EClass getAddElement();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.jppjson.myDsl.AddElement#getElement <em>Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Element</em>'.
   * @see org.xtext.example.jppjson.myDsl.AddElement#getElement()
   * @see #getAddElement()
   * @generated
   */
  EReference getAddElement_Element();

  /**
   * Returns the meta object for class '{@link org.xtext.example.jppjson.myDsl.RemoveElement <em>Remove Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Remove Element</em>'.
   * @see org.xtext.example.jppjson.myDsl.RemoveElement
   * @generated
   */
  EClass getRemoveElement();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.jppjson.myDsl.RemoveElement#getKey <em>Key</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Key</em>'.
   * @see org.xtext.example.jppjson.myDsl.RemoveElement#getKey()
   * @see #getRemoveElement()
   * @generated
   */
  EAttribute getRemoveElement_Key();

  /**
   * Returns the meta object for class '{@link org.xtext.example.jppjson.myDsl.EditObject <em>Edit Object</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Edit Object</em>'.
   * @see org.xtext.example.jppjson.myDsl.EditObject
   * @generated
   */
  EClass getEditObject();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.jppjson.myDsl.EditObject#getKey <em>Key</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Key</em>'.
   * @see org.xtext.example.jppjson.myDsl.EditObject#getKey()
   * @see #getEditObject()
   * @generated
   */
  EAttribute getEditObject_Key();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.jppjson.myDsl.EditObject#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Value</em>'.
   * @see org.xtext.example.jppjson.myDsl.EditObject#getValue()
   * @see #getEditObject()
   * @generated
   */
  EReference getEditObject_Value();

  /**
   * Returns the meta object for class '{@link org.xtext.example.jppjson.myDsl.ToString <em>To String</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>To String</em>'.
   * @see org.xtext.example.jppjson.myDsl.ToString
   * @generated
   */
  EClass getToString();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.jppjson.myDsl.ToString#getPath <em>Path</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Path</em>'.
   * @see org.xtext.example.jppjson.myDsl.ToString#getPath()
   * @see #getToString()
   * @generated
   */
  EAttribute getToString_Path();

  /**
   * Returns the meta object for class '{@link org.xtext.example.jppjson.myDsl.ToCSV <em>To CSV</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>To CSV</em>'.
   * @see org.xtext.example.jppjson.myDsl.ToCSV
   * @generated
   */
  EClass getToCSV();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.jppjson.myDsl.ToCSV#getPath <em>Path</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Path</em>'.
   * @see org.xtext.example.jppjson.myDsl.ToCSV#getPath()
   * @see #getToCSV()
   * @generated
   */
  EAttribute getToCSV_Path();

  /**
   * Returns the meta object for class '{@link org.xtext.example.jppjson.myDsl.Expression <em>Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Expression</em>'.
   * @see org.xtext.example.jppjson.myDsl.Expression
   * @generated
   */
  EClass getExpression();

  /**
   * Returns the meta object for class '{@link org.xtext.example.jppjson.myDsl.Entity <em>Entity</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Entity</em>'.
   * @see org.xtext.example.jppjson.myDsl.Entity
   * @generated
   */
  EClass getEntity();

  /**
   * Returns the meta object for class '{@link org.xtext.example.jppjson.myDsl.Element <em>Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Element</em>'.
   * @see org.xtext.example.jppjson.myDsl.Element
   * @generated
   */
  EClass getElement();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.jppjson.myDsl.Element#getKey <em>Key</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Key</em>'.
   * @see org.xtext.example.jppjson.myDsl.Element#getKey()
   * @see #getElement()
   * @generated
   */
  EAttribute getElement_Key();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.jppjson.myDsl.Element#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Value</em>'.
   * @see org.xtext.example.jppjson.myDsl.Element#getValue()
   * @see #getElement()
   * @generated
   */
  EReference getElement_Value();

  /**
   * Returns the meta object for class '{@link org.xtext.example.jppjson.myDsl.Value <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Value</em>'.
   * @see org.xtext.example.jppjson.myDsl.Value
   * @generated
   */
  EClass getValue();

  /**
   * Returns the meta object for class '{@link org.xtext.example.jppjson.myDsl.JsonString <em>Json String</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Json String</em>'.
   * @see org.xtext.example.jppjson.myDsl.JsonString
   * @generated
   */
  EClass getJsonString();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.jppjson.myDsl.JsonString#getVal <em>Val</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Val</em>'.
   * @see org.xtext.example.jppjson.myDsl.JsonString#getVal()
   * @see #getJsonString()
   * @generated
   */
  EAttribute getJsonString_Val();

  /**
   * Returns the meta object for class '{@link org.xtext.example.jppjson.myDsl.JsonBoolean <em>Json Boolean</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Json Boolean</em>'.
   * @see org.xtext.example.jppjson.myDsl.JsonBoolean
   * @generated
   */
  EClass getJsonBoolean();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.jppjson.myDsl.JsonBoolean#getVal <em>Val</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Val</em>'.
   * @see org.xtext.example.jppjson.myDsl.JsonBoolean#getVal()
   * @see #getJsonBoolean()
   * @generated
   */
  EAttribute getJsonBoolean_Val();

  /**
   * Returns the meta object for class '{@link org.xtext.example.jppjson.myDsl.JsonEmpty <em>Json Empty</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Json Empty</em>'.
   * @see org.xtext.example.jppjson.myDsl.JsonEmpty
   * @generated
   */
  EClass getJsonEmpty();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.jppjson.myDsl.JsonEmpty#getVal <em>Val</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Val</em>'.
   * @see org.xtext.example.jppjson.myDsl.JsonEmpty#getVal()
   * @see #getJsonEmpty()
   * @generated
   */
  EAttribute getJsonEmpty_Val();

  /**
   * Returns the meta object for class '{@link org.xtext.example.jppjson.myDsl.JsonInteger <em>Json Integer</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Json Integer</em>'.
   * @see org.xtext.example.jppjson.myDsl.JsonInteger
   * @generated
   */
  EClass getJsonInteger();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.jppjson.myDsl.JsonInteger#getVal <em>Val</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Val</em>'.
   * @see org.xtext.example.jppjson.myDsl.JsonInteger#getVal()
   * @see #getJsonInteger()
   * @generated
   */
  EAttribute getJsonInteger_Val();

  /**
   * Returns the meta object for class '{@link org.xtext.example.jppjson.myDsl.JObject <em>JObject</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>JObject</em>'.
   * @see org.xtext.example.jppjson.myDsl.JObject
   * @generated
   */
  EClass getJObject();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.jppjson.myDsl.JObject#getElement <em>Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Element</em>'.
   * @see org.xtext.example.jppjson.myDsl.JObject#getElement()
   * @see #getJObject()
   * @generated
   */
  EReference getJObject_Element();

  /**
   * Returns the meta object for class '{@link org.xtext.example.jppjson.myDsl.JArray <em>JArray</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>JArray</em>'.
   * @see org.xtext.example.jppjson.myDsl.JArray
   * @generated
   */
  EClass getJArray();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.jppjson.myDsl.JArray#getExpression <em>Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Expression</em>'.
   * @see org.xtext.example.jppjson.myDsl.JArray#getExpression()
   * @see #getJArray()
   * @generated
   */
  EReference getJArray_Expression();

  /**
   * Returns the meta object for class '{@link org.xtext.example.jppjson.myDsl.BinExp <em>Bin Exp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Bin Exp</em>'.
   * @see org.xtext.example.jppjson.myDsl.BinExp
   * @generated
   */
  EClass getBinExp();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.jppjson.myDsl.BinExp#getVal <em>Val</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Val</em>'.
   * @see org.xtext.example.jppjson.myDsl.BinExp#getVal()
   * @see #getBinExp()
   * @generated
   */
  EAttribute getBinExp_Val();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.jppjson.myDsl.BinExp#getRval <em>Rval</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Rval</em>'.
   * @see org.xtext.example.jppjson.myDsl.BinExp#getRval()
   * @see #getBinExp()
   * @generated
   */
  EAttribute getBinExp_Rval();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  MyDslFactory getMyDslFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.example.jppjson.myDsl.impl.ProgrammeImpl <em>Programme</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.jppjson.myDsl.impl.ProgrammeImpl
     * @see org.xtext.example.jppjson.myDsl.impl.MyDslPackageImpl#getProgramme()
     * @generated
     */
    EClass PROGRAMME = eINSTANCE.getProgramme();

    /**
     * The meta object literal for the '<em><b>Loadfiles</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROGRAMME__LOADFILES = eINSTANCE.getProgramme_Loadfiles();

    /**
     * The meta object literal for the '{@link org.xtext.example.jppjson.myDsl.impl.LoadfileImpl <em>Loadfile</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.jppjson.myDsl.impl.LoadfileImpl
     * @see org.xtext.example.jppjson.myDsl.impl.MyDslPackageImpl#getLoadfile()
     * @generated
     */
    EClass LOADFILE = eINSTANCE.getLoadfile();

    /**
     * The meta object literal for the '<em><b>Path</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LOADFILE__PATH = eINSTANCE.getLoadfile_Path();

    /**
     * The meta object literal for the '<em><b>Commands</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LOADFILE__COMMANDS = eINSTANCE.getLoadfile_Commands();

    /**
     * The meta object literal for the '{@link org.xtext.example.jppjson.myDsl.impl.CommandImpl <em>Command</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.jppjson.myDsl.impl.CommandImpl
     * @see org.xtext.example.jppjson.myDsl.impl.MyDslPackageImpl#getCommand()
     * @generated
     */
    EClass COMMAND = eINSTANCE.getCommand();

    /**
     * The meta object literal for the '{@link org.xtext.example.jppjson.myDsl.impl.ReadImpl <em>Read</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.jppjson.myDsl.impl.ReadImpl
     * @see org.xtext.example.jppjson.myDsl.impl.MyDslPackageImpl#getRead()
     * @generated
     */
    EClass READ = eINSTANCE.getRead();

    /**
     * The meta object literal for the '<em><b>Path</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute READ__PATH = eINSTANCE.getRead_Path();

    /**
     * The meta object literal for the '{@link org.xtext.example.jppjson.myDsl.impl.AddElementImpl <em>Add Element</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.jppjson.myDsl.impl.AddElementImpl
     * @see org.xtext.example.jppjson.myDsl.impl.MyDslPackageImpl#getAddElement()
     * @generated
     */
    EClass ADD_ELEMENT = eINSTANCE.getAddElement();

    /**
     * The meta object literal for the '<em><b>Element</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ADD_ELEMENT__ELEMENT = eINSTANCE.getAddElement_Element();

    /**
     * The meta object literal for the '{@link org.xtext.example.jppjson.myDsl.impl.RemoveElementImpl <em>Remove Element</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.jppjson.myDsl.impl.RemoveElementImpl
     * @see org.xtext.example.jppjson.myDsl.impl.MyDslPackageImpl#getRemoveElement()
     * @generated
     */
    EClass REMOVE_ELEMENT = eINSTANCE.getRemoveElement();

    /**
     * The meta object literal for the '<em><b>Key</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute REMOVE_ELEMENT__KEY = eINSTANCE.getRemoveElement_Key();

    /**
     * The meta object literal for the '{@link org.xtext.example.jppjson.myDsl.impl.EditObjectImpl <em>Edit Object</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.jppjson.myDsl.impl.EditObjectImpl
     * @see org.xtext.example.jppjson.myDsl.impl.MyDslPackageImpl#getEditObject()
     * @generated
     */
    EClass EDIT_OBJECT = eINSTANCE.getEditObject();

    /**
     * The meta object literal for the '<em><b>Key</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EDIT_OBJECT__KEY = eINSTANCE.getEditObject_Key();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EDIT_OBJECT__VALUE = eINSTANCE.getEditObject_Value();

    /**
     * The meta object literal for the '{@link org.xtext.example.jppjson.myDsl.impl.ToStringImpl <em>To String</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.jppjson.myDsl.impl.ToStringImpl
     * @see org.xtext.example.jppjson.myDsl.impl.MyDslPackageImpl#getToString()
     * @generated
     */
    EClass TO_STRING = eINSTANCE.getToString();

    /**
     * The meta object literal for the '<em><b>Path</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TO_STRING__PATH = eINSTANCE.getToString_Path();

    /**
     * The meta object literal for the '{@link org.xtext.example.jppjson.myDsl.impl.ToCSVImpl <em>To CSV</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.jppjson.myDsl.impl.ToCSVImpl
     * @see org.xtext.example.jppjson.myDsl.impl.MyDslPackageImpl#getToCSV()
     * @generated
     */
    EClass TO_CSV = eINSTANCE.getToCSV();

    /**
     * The meta object literal for the '<em><b>Path</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TO_CSV__PATH = eINSTANCE.getToCSV_Path();

    /**
     * The meta object literal for the '{@link org.xtext.example.jppjson.myDsl.impl.ExpressionImpl <em>Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.jppjson.myDsl.impl.ExpressionImpl
     * @see org.xtext.example.jppjson.myDsl.impl.MyDslPackageImpl#getExpression()
     * @generated
     */
    EClass EXPRESSION = eINSTANCE.getExpression();

    /**
     * The meta object literal for the '{@link org.xtext.example.jppjson.myDsl.impl.EntityImpl <em>Entity</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.jppjson.myDsl.impl.EntityImpl
     * @see org.xtext.example.jppjson.myDsl.impl.MyDslPackageImpl#getEntity()
     * @generated
     */
    EClass ENTITY = eINSTANCE.getEntity();

    /**
     * The meta object literal for the '{@link org.xtext.example.jppjson.myDsl.impl.ElementImpl <em>Element</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.jppjson.myDsl.impl.ElementImpl
     * @see org.xtext.example.jppjson.myDsl.impl.MyDslPackageImpl#getElement()
     * @generated
     */
    EClass ELEMENT = eINSTANCE.getElement();

    /**
     * The meta object literal for the '<em><b>Key</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ELEMENT__KEY = eINSTANCE.getElement_Key();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ELEMENT__VALUE = eINSTANCE.getElement_Value();

    /**
     * The meta object literal for the '{@link org.xtext.example.jppjson.myDsl.impl.ValueImpl <em>Value</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.jppjson.myDsl.impl.ValueImpl
     * @see org.xtext.example.jppjson.myDsl.impl.MyDslPackageImpl#getValue()
     * @generated
     */
    EClass VALUE = eINSTANCE.getValue();

    /**
     * The meta object literal for the '{@link org.xtext.example.jppjson.myDsl.impl.JsonStringImpl <em>Json String</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.jppjson.myDsl.impl.JsonStringImpl
     * @see org.xtext.example.jppjson.myDsl.impl.MyDslPackageImpl#getJsonString()
     * @generated
     */
    EClass JSON_STRING = eINSTANCE.getJsonString();

    /**
     * The meta object literal for the '<em><b>Val</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute JSON_STRING__VAL = eINSTANCE.getJsonString_Val();

    /**
     * The meta object literal for the '{@link org.xtext.example.jppjson.myDsl.impl.JsonBooleanImpl <em>Json Boolean</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.jppjson.myDsl.impl.JsonBooleanImpl
     * @see org.xtext.example.jppjson.myDsl.impl.MyDslPackageImpl#getJsonBoolean()
     * @generated
     */
    EClass JSON_BOOLEAN = eINSTANCE.getJsonBoolean();

    /**
     * The meta object literal for the '<em><b>Val</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute JSON_BOOLEAN__VAL = eINSTANCE.getJsonBoolean_Val();

    /**
     * The meta object literal for the '{@link org.xtext.example.jppjson.myDsl.impl.JsonEmptyImpl <em>Json Empty</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.jppjson.myDsl.impl.JsonEmptyImpl
     * @see org.xtext.example.jppjson.myDsl.impl.MyDslPackageImpl#getJsonEmpty()
     * @generated
     */
    EClass JSON_EMPTY = eINSTANCE.getJsonEmpty();

    /**
     * The meta object literal for the '<em><b>Val</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute JSON_EMPTY__VAL = eINSTANCE.getJsonEmpty_Val();

    /**
     * The meta object literal for the '{@link org.xtext.example.jppjson.myDsl.impl.JsonIntegerImpl <em>Json Integer</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.jppjson.myDsl.impl.JsonIntegerImpl
     * @see org.xtext.example.jppjson.myDsl.impl.MyDslPackageImpl#getJsonInteger()
     * @generated
     */
    EClass JSON_INTEGER = eINSTANCE.getJsonInteger();

    /**
     * The meta object literal for the '<em><b>Val</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute JSON_INTEGER__VAL = eINSTANCE.getJsonInteger_Val();

    /**
     * The meta object literal for the '{@link org.xtext.example.jppjson.myDsl.impl.JObjectImpl <em>JObject</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.jppjson.myDsl.impl.JObjectImpl
     * @see org.xtext.example.jppjson.myDsl.impl.MyDslPackageImpl#getJObject()
     * @generated
     */
    EClass JOBJECT = eINSTANCE.getJObject();

    /**
     * The meta object literal for the '<em><b>Element</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference JOBJECT__ELEMENT = eINSTANCE.getJObject_Element();

    /**
     * The meta object literal for the '{@link org.xtext.example.jppjson.myDsl.impl.JArrayImpl <em>JArray</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.jppjson.myDsl.impl.JArrayImpl
     * @see org.xtext.example.jppjson.myDsl.impl.MyDslPackageImpl#getJArray()
     * @generated
     */
    EClass JARRAY = eINSTANCE.getJArray();

    /**
     * The meta object literal for the '<em><b>Expression</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference JARRAY__EXPRESSION = eINSTANCE.getJArray_Expression();

    /**
     * The meta object literal for the '{@link org.xtext.example.jppjson.myDsl.impl.BinExpImpl <em>Bin Exp</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.jppjson.myDsl.impl.BinExpImpl
     * @see org.xtext.example.jppjson.myDsl.impl.MyDslPackageImpl#getBinExp()
     * @generated
     */
    EClass BIN_EXP = eINSTANCE.getBinExp();

    /**
     * The meta object literal for the '<em><b>Val</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BIN_EXP__VAL = eINSTANCE.getBinExp_Val();

    /**
     * The meta object literal for the '<em><b>Rval</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BIN_EXP__RVAL = eINSTANCE.getBinExp_Rval();

  }

} //MyDslPackage
