/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.jppjson.myDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Programme</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.jppjson.myDsl.Programme#getLoadfiles <em>Loadfiles</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.jppjson.myDsl.MyDslPackage#getProgramme()
 * @model
 * @generated
 */
public interface Programme extends EObject
{
  /**
   * Returns the value of the '<em><b>Loadfiles</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.jppjson.myDsl.Loadfile}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Loadfiles</em>' containment reference list.
   * @see org.xtext.example.jppjson.myDsl.MyDslPackage#getProgramme_Loadfiles()
   * @model containment="true"
   * @generated
   */
  EList<Loadfile> getLoadfiles();

} // Programme
