/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.jppjson.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>To JSON</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.jppjson.myDsl.MyDslPackage#getToJSON()
 * @model
 * @generated
 */
public interface ToJSON extends Command
{
} // ToJSON
