/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.jppjson.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Value</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.jppjson.myDsl.MyDslPackage#getValue()
 * @model
 * @generated
 */
public interface Value extends Expression
{
} // Value
