/*
 * generated by Xtext 2.25.0
 */
package org.xtext.example.jppjson.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import org.xtext.example.jppjson.ui.internal.JppjsonActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class MyDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(JppjsonActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		JppjsonActivator activator = JppjsonActivator.getInstance();
		return activator != null ? activator.getInjector(JppjsonActivator.ORG_XTEXT_EXAMPLE_JPPJSON_MYDSL) : null;
	}

}
