/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.jppjson.myDsl.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.example.jppjson.myDsl.MyDslPackage;
import org.xtext.example.jppjson.myDsl.Read;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Read</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ReadImpl extends CommandImpl implements Read
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ReadImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.READ;
  }

} //ReadImpl
