/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.jppjson.myDsl.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.example.jppjson.myDsl.MyDslPackage;
import org.xtext.example.jppjson.myDsl.ToJSON;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>To JSON</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ToJSONImpl extends CommandImpl implements ToJSON
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ToJSONImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.TO_JSON;
  }

} //ToJSONImpl
